[phases.setup]
nixPkgs = ["python311"]
aptPkgs = ["tesseract-ocr"]

[phases.install]
cmds = ["pip install --no-cache-dir --prefer-binary -r requirements.txt"]
cacheDirectories = ["/root/.cache/pip"]

[start]
cmd = "python server.py"
