import runpy
from pathlib import Path

ROOT = Path(__file__).resolve().parent

# iOS Safari: keep the working native overscroll fix untouched.
app_js = ROOT / "public" / "js" / "app.js"
source = app_js.read_text(encoding="utf-8")
marker = "// ── Pull-to-refresh suppression (iOS Safari) ──"
pos = source.find(marker)
if pos < 0:
    raise RuntimeError("iOS PTR handler marker missing")
source = source[:pos].rstrip() + "\n"
app_js.write_text(source, encoding="utf-8")

styles = ROOT / "public" / "css" / "styles.css"
css = styles.read_text(encoding="utf-8")
css += r'''

/* iOS Safari pull-to-refresh boundary. */
@media (max-width: 768px) {
  #login-screen.active {
    height: 100dvh;
    min-height: 100dvh;
    overflow-y: scroll;
    overscroll-behavior-y: contain;
    -webkit-overflow-scrolling: touch;
  }
  #login-screen.active::after {
    content: '';
    display: block;
    height: 1px;
    width: 1px;
    pointer-events: none;
  }
}
'''
styles.write_text(css, encoding="utf-8")

index_html = ROOT / "public" / "index.html"
index = index_html.read_text(encoding="utf-8")
index = index.replace("/js/app.js?v=20260917_login04", "/js/app.js?v=20260917_ptr06", 1)
index = index.replace("/css/styles.css?v=20260917_login04", "/css/styles.css?v=20260917_ptr06", 1)

# Do not let Safari/app startup raise the keyboard at all. Blurring after focus
# is visibly too late: the keyboard has already begun animating. Instead, login
# text controls are temporarily read-only before deferred app.js can run.
# A real touch/pointer removes readOnly synchronously on touchstart/pointerdown,
# before Safari performs the focus generated by that same user gesture.
keyboard_guard = r'''
    <script>
    (function () {
        if (!window.matchMedia('(max-width: 768px)').matches) return;

        var armed = false;
        function loginFields() {
            return document.querySelectorAll('#login-screen input, #login-screen textarea');
        }
        function lockLoginFields() {
            if (armed) return;
            loginFields().forEach(function (el) {
                if (!el.readOnly) {
                    el.readOnly = true;
                    el.dataset.aulaStartupReadonly = '1';
                }
            });
        }
        function unlockLoginFields() {
            if (armed) return;
            armed = true;
            loginFields().forEach(function (el) {
                if (el.dataset.aulaStartupReadonly === '1') {
                    el.readOnly = false;
                    delete el.dataset.aulaStartupReadonly;
                }
            });
            observer.disconnect();
        }

        var observer = new MutationObserver(lockLoginFields);
        observer.observe(document.documentElement, { childList: true, subtree: true });
        document.addEventListener('DOMContentLoaded', lockLoginFields, { once: true });
        document.addEventListener('touchstart', unlockLoginFields, { capture: true, passive: true, once: true });
        document.addEventListener('pointerdown', unlockLoginFields, { capture: true, passive: true, once: true });
    })();
    </script>
'''
anchor = '<script src="/js/bilingual_materials.js?v=20260911_v016" defer></script>'
if anchor not in index:
    raise RuntimeError("script anchor missing")
index = index.replace(anchor, keyboard_guard + "\n    " + anchor, 1)
index_html.write_text(index, encoding="utf-8")

server = ROOT / "server.py"
print("[BOOT] applied native iOS overscroll boundary + pre-focus mobile keyboard guard")
print("[BOOT] starting AulaAI")
runpy.run_path(str(server), run_name="__main__")
